namespace Mvvm.Framework.Core
{
    // ========== CanExecuteRequested ==========
    runtimeclass CanExecuteRequestedEventArgs
    {
        CanExecuteRequestedEventArgs(Object parameter);

        Object Parameter { get; };
        Boolean Handled { get; set; };
    }

    // ========== CanExecuteCompleted ==========
    runtimeclass CanExecuteCompletedEventArgs
    {
        CanExecuteCompletedEventArgs(Object parameter, Boolean result);

        Object Parameter { get; };
        Boolean Result { get; };
    }

    // ========== ExecuteRequested ==========
    runtimeclass ExecuteRequestedEventArgs
    {
        ExecuteRequestedEventArgs(Object parameter);

        Object Parameter { get; };
    }

    // ========== ExecuteCompleted ==========
    runtimeclass ExecuteCompletedEventArgs
    {
        ExecuteCompletedEventArgs(Object parameter, Int32 hresult);

        Object Parameter { get; };
        Boolean Succeeded { get; };
        Int32 Error { get; };
    }
}
