namespace WinUI3MVVMSample1
{
    [default_interface]
    runtimeclass MyEntityViewModel
        : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MyEntityViewModel();
        Int32 MyProperty;
        void IncrementProperty();
        Microsoft.UI.Xaml.Input.ICommand ResetCommand;
    }
}
